### ISSUE TITLE
Does not seem to able to interface with asana

### ISSUE THREAD

**Issue by charleswolfe** [codeallthethingz/asana-github-pr-webhook#18]
I followed the instructions, was very easy. 
Github shows that the webhook is being called, and it returned `it worked` in the body of the response, but nothing is posted to asana and the Pr doesnt get updated with asana details

**Comment by charleswolfe** [comment]
In the asanator.js file, the gid needs to be changed
thats should probably come from a conf file

**Comment by charleswolfe** [comment]
closing issue, but you should still fix it. this is a cool tool

**Comment by IliasDeros** [comment]
✅The GID was extracted to a variable in https://github.com/codeallthethingz/asana-github-pr-webhook/commit/c968833ceff0a8e011c002f89f63df3f9df3c938#diff-3ead76602b609db75229bdcabebdb9b8
